=== finley243/adventure-engine/src/gamefiles/schemas/actions.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="data">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="action" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="prompt" type="xs:string"/>
                            <xs:element name="parameter" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="name" type="xs:string" use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="condition" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="blockMessage" type="xs:string" minOccurs="0"/>
                                        <xs:element name="script" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="conditionShow" minOccurs="0"/>
                            <xs:element name="script" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                        <xs:attribute name="actionPoints" type="xs:integer"/>
                    </xs:complexType>
                    <xs:unique name="uniqueParamName">
                        <xs:selector xpath="parameter"/>
                        <xs:field xpath="@name"/>
                    </xs:unique>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueID">
            <xs:selector xpath="action"/>
            <xs:field xpath="@id"/>
        </xs:unique>
    </xs:element>

</xs:schema>

=== finley243/adventure-engine/src/gamefiles/data/actions.xml
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/actions.xsd">
    <action id="lock_pick">
        <prompt>Pick lock</prompt>
        <condition>
            <blockMessage>Unlocked</blockMessage>
            <script>stat.parentObject.locked</script>
        </condition>
        <condition>
            <blockMessage>Higher lockpick skill required</blockMessage>
            <script>stat.subject.skill_lockpick &gt;= stat.parentObject.lock_pick_difficulty</script>
        </condition>
        <script>
            stat.parentObject.locked = false;
            sendSensoryEvent(area=stat.subject.area.id, phrase="pickLock");
        </script>
    </action>
    <action id="lock_key">
        <prompt>Unlock</prompt>
        <condition>
            <blockMessage>Unlocked</blockMessage>
            <script>stat.parentObject.locked</script>
        </condition>
        <condition>
            <blockMessage>No valid key in inventory</blockMessage>
            <script>stat.parentObject.lock_keys != null &amp;&amp; inventoryContains(inventory=stat.subject.inventory, item=stat.parentObject.lock_keys)</script>
        </condition>
        <script>
            stat.parentObject.locked = false;
            sendSensoryEvent(area=stat.subject.area.id, phrase="unlock");
        </script>
    </action>
    <action id="vending_machine">
        <prompt>Buy $itemName ($price)</prompt>
        <parameter name="itemName">stat.itemTemplate(itemID).name</parameter>
        <parameter name="price">stat.parentObject.price_hacked ? "0" : toString(value=stat.itemTemplate(itemID).price)</parameter>
        <condition>
            <blockMessage>Not enough credits</blockMessage>
            <script>stat.subject.money &gt;= stat.itemTemplate(itemID).price</script>
        </condition>
        <script>
            transferItem(to=stat.subject.inventory, item=itemID);
            if (!stat.parentObject.price_hacked) {
                stat.subject.money = stat.subject.money - stat.itemTemplate(itemID).price;
            }
            var item = stat.itemTemplate(itemID).noun;
            sendSensoryEvent(area=stat.subject.area.id, phrase="vendingMachineBuy", item=item);
        </script>
    </action>
    <action id="move_basic">
        <prompt>$areaName ($dir)</prompt>
        <parameter name="areaName">statHolder.parentArea.room != null &amp;&amp; (statHolder.subject.area.room == null || stat.subject.area.room.id != stat.parentArea.room.id) ? stat.parentArea.room.name : stat.parentArea.name</parameter>
        <script>
            var originAreaID = stat.subject.area.id;
            var targetArea = stat.parentArea.noun;
            sendSensoryEvent(area=set(originAreaID, stat.parentArea.id), phrase=stat.parentArea.move_phrase, targetArea=targetArea, dirName=dirName);
            stat.subject.area = stat.parentArea.id;
        </script>
    </action>
    <action id="move_corner">
        <prompt>$areaName (Around corner, $dir)</prompt>
        <script>
            var originAreaID = stat.subject.area.id;
            var targetArea = stat.parentArea.noun;
            sendSensoryEvent(area=originAreaID, phrase="moveCorner", targetArea=targetArea);
            stat.subject.area = stat.parentArea.id;
            sendSensoryEvent(area=stat.parentArea.id, phrase="moveCorner", detectSelf=false, targetArea=targetArea);
        </script>
    </action>
    <action id="move_door">
        <prompt>$areaName (Through $doorName, $dir)</prompt>
        <parameter name="doorName">stat.parentObject.name</parameter>
        <parameter name="areaName">statHolder.parentArea.room != null &amp;&amp; (statHolder.subject.area.room == null || stat.subject.area.room.id != stat.parentArea.room.id) ? stat.parentArea.room.name : stat.parentArea.name</parameter>
        <condition>
            <blockMessage>Locked</blockMessage>
            <script>stat.parentObject.locked == null || !stat.parentObject.locked</script>
        </condition>
        <script>
            var originAreaID = stat.subject.area.id;
            var targetArea = stat.parentArea.noun;
            var originRoomID = statHolder.subject.area.room != null ? stat.subject.area.room.id : null;
            var targetRoomID = statHolder.parentArea.room != null ? stat.parentArea.room.id : null;
            var originArea = originRoomID != null &amp;&amp; originRoomID != targetRoomID ? stat.subject.area.room.noun : stat.subject.area.noun;
            var door = stat.parentObject.noun;
            sendSensoryEvent(area=originAreaID, phrase="moveThrough", targetArea=targetArea, originArea=originArea, door=door);
            stat.subject.area = stat.parentArea.id;
            sendSensoryEvent(area=stat.parentArea.id, phrase="moveThroughReverse", detectSelf=false, targetArea=targetArea, originArea=originArea, door=door);
        </script>
    </action>
    <action id="drive">
        <prompt>Drive</prompt>
        <parameter name="areaName">stat.parentArea.name</parameter>
        <script>
            var targetArea = stat.parentArea.noun;
            var vehicle = stat.parentObject.noun;
            sendSensoryEvent(phrase="driveTo", area=set(stat.subject.area.id, stat.parentArea.id), targetArea=targetArea, vehicle=vehicle);
            stat.parentObject.area = stat.parentArea.id;
        </script>
    </action>
    <action id="drive_corner">
        <prompt>Drive</prompt>
        <script>
            var targetArea = stat.parentArea.noun;
            var vehicle = stat.parentObject.noun;
            sendSensoryEvent(phrase="driveCorner", area=set(stat.subject.area.id, stat.parentArea.id), targetArea=targetArea, vehicle=vehicle);
            stat.parentObject.area = stat.parentArea.id;
        </script>
    </action>
    <action id="vending_machine_hack_price">
        <prompt>Hack Price</prompt>
        <condition>
            <script>!stat.parentObject.price_hacked</script>
        </condition>
        <script>stat.parentObject.price_hacked = true;</script>
    </action>
</data>

=== finley243/adventure-engine/src/gamefiles/data/actions_move_vehicle.xml
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/actions.xsd">
    <action id="drive">
        <prompt>Drive</prompt>
        <parameter name="areaName">stat.parentArea.name</parameter>
        <script>
            var targetArea = stat.parentArea.noun;
            var vehicle = stat.parentObject.noun;
            sendSensoryEvent(phrase="driveTo", area=set(stat.subject.area.id, stat.parentArea.id), targetArea=targetArea, vehicle=vehicle);
            stat.parentObject.area = stat.parentArea.id;
        </script>
    </action>
    <action id="drive_corner">
        <prompt>Drive</prompt>
        <script>
            var targetArea = stat.parentArea.noun;
            var vehicle = stat.parentObject.noun;
            sendSensoryEvent(phrase="driveCorner", area=set(stat.subject.area.id, stat.parentArea.id), targetArea=targetArea, vehicle=vehicle);
            stat.parentObject.area = stat.parentArea.id;
        </script>
    </action>
</data>

=== finley243/adventure-engine/src/gamefiles/data/actions_move.xml
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/actions.xsd">
    <action id="move_basic">
        <prompt>$areaName ($dir)</prompt>
        <parameter name="areaName">statHolder.parentArea.room != null &amp;&amp; (statHolder.subject.area.room == null || stat.subject.area.room.id != stat.parentArea.room.id) ? stat.parentArea.room.name : stat.parentArea.name</parameter>
        <script>
            var originAreaID = stat.subject.area.id;
            var targetArea = stat.parentArea.noun;
            sendSensoryEvent(area=set(originAreaID, stat.parentArea.id), phrase=stat.parentArea.move_phrase, targetArea=targetArea, dirName=dirName);
            stat.subject.area = stat.parentArea.id;
        </script>
    </action>
    <action id="move_corner">
        <prompt>$areaName (Around corner, $dir)</prompt>
        <script>
            var originAreaID = stat.subject.area.id;
            var targetArea = stat.parentArea.noun;
            sendSensoryEvent(area=originAreaID, phrase="moveCorner", targetArea=targetArea);
            stat.subject.area = stat.parentArea.id;
            sendSensoryEvent(area=stat.parentArea.id, phrase="moveCorner", detectSelf=false, targetArea=targetArea);
        </script>
    </action>
    <action id="move_door">
        <prompt>$areaName (Through $doorName, $dir)</prompt>
        <parameter name="doorName">stat.parentObject.name</parameter>
        <parameter name="areaName">statHolder.parentArea.room != null &amp;&amp; (statHolder.subject.area.room == null || stat.subject.area.room.id != stat.parentArea.room.id) ? stat.parentArea.room.name : stat.parentArea.name</parameter>
        <condition>
            <blockMessage>Locked</blockMessage>
            <script>stat.parentObject.locked == null || !stat.parentObject.locked</script>
        </condition>
        <script>
            var originAreaID = stat.subject.area.id;
            var targetArea = stat.parentArea.noun;
            var originRoomID = statHolder.subject.area.room != null ? stat.subject.area.room.id : null;
            var targetRoomID = statHolder.parentArea.room != null ? stat.parentArea.room.id : null;
            var originArea = originRoomID != null &amp;&amp; originRoomID != targetRoomID ? stat.subject.area.room.noun : stat.subject.area.noun;
            var door = stat.parentObject.noun;
            sendSensoryEvent(area=originAreaID, phrase="moveThrough", targetArea=targetArea, originArea=originArea, door=door);
            stat.subject.area = stat.parentArea.id;
            sendSensoryEvent(area=stat.parentArea.id, phrase="moveThroughReverse", detectSelf=false, targetArea=targetArea, originArea=originArea, door=door);
        </script>
    </action>
</data>
