=== finley243/adventure-engine/src/gamefiles/schemas/areas.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:include schemaLocation="common.xsd"/>

    <xs:element name="data">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="area" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="type" type="xs:string"/>
                                            <xs:attribute name="plural" type="xs:boolean"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="description" type="SceneLine" minOccurs="0"/>
                            <xs:element name="link" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="type" type="xs:string"/>
                                    <xs:attribute name="dist" type="DistanceCategory"/>
                                    <xs:attribute name="dir" type="CompassDirection"/>
                                    <xs:attribute name="area" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="object" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="localVar" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="name" type="xs:string" use="required"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="objectLink" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:attribute name="link" type="xs:string" use="required"/>
                                                <xs:attribute name="object" type="xs:string" use="required"/>
                                                <xs:attribute name="dir" type="CompassDirection"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="vehicleObjectOverride" type="xs:string" minOccurs="0"/>
                                        <xs:element name="networkID" type="xs:string" minOccurs="0"/>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:string" use="required"/>
                                    <xs:attribute name="template" type="xs:string" use="required"/>
                                    <xs:attribute name="startDisabled" type="xs:boolean"/>
                                    <xs:attribute name="startHidden" type="xs:boolean"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="actor" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="descriptor" type="xs:string" minOccurs="0"/>
                                        <xs:element name="behaviors" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="behavior" type="Behavior" maxOccurs="unbounded"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:string" use="required"/>
                                    <xs:attribute name="template" type="xs:string" use="required"/>
                                    <xs:attribute name="startDead" type="xs:boolean"/>
                                    <xs:attribute name="startDisabled" type="xs:boolean"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                        <xs:attribute name="room" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueID">
            <xs:selector xpath="area"/>
            <xs:field xpath="@id"/>
        </xs:unique>
        <xs:unique name="uniqueObjectID">
            <xs:selector xpath="area/object"/>
            <xs:field xpath="@id"/>
        </xs:unique>
        <xs:unique name="uniqueActorID">
            <xs:selector xpath="area/actor"/>
            <xs:field xpath="@id"/>
        </xs:unique>
        <xs:unique name="uniqueItemID">
            <xs:selector xpath="area/item"/>
            <xs:field xpath="@id"/>
        </xs:unique>
    </xs:element>

    <xs:complexType name="Behavior">
        <xs:sequence>
            <xs:element name="behavior" type="Behavior" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="idle" type="Idle" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="type" type="xs:string"/>
        <xs:attribute name="isCycle" type="xs:boolean"/>
        <xs:attribute name="duration" type="xs:integer"/>
        <xs:attribute name="area" type="xs:string"/>
        <xs:attribute name="object" type="xs:string"/>
        <xs:attribute name="slot" type="xs:string"/>
        <xs:attribute name="actor" type="xs:string"/>
        <xs:attribute name="action" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="Idle">
        <xs:sequence>
            <xs:element name="condition" type="xs:string" minOccurs="0"/>
            <xs:element name="phrase" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== finley243/adventure-engine/src/gamefiles/data/world_providence_hq.xml
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/areas.xsd">
    <area id="providence_lobby_entrance" room="providence_lobby">
        <name type="near">entrance</name>
        <link type="basic" dist="CLOSE" dir="N" area="providence_lobby_reception"/>
    </area>
    <area id="providence_lobby_reception" room="providence_lobby">
        <name type="near">reception desk</name>
        <link type="basic" dist="CLOSE" dir="S" area="providence_lobby_entrance"/>
        <link type="basic" dist="CLOSE" dir="N" area="providence_lobby_elevators"/>
        <link type="basic" dist="CLOSE" dir="E" area="providence_lobby_showroom"/>
        <object id="providence_lobby_reception_restroom_door" template="door_basic">
            <localVar name="door_link_object">"providence_lobby_restroom_door"</localVar>
            <localVar name="door_link_dir">"W"</localVar>
        </object>
        <actor id="providence_receptionist" template="enemy_melee"/>
    </area>
    <area id="providence_lobby_elevators" room="providence_lobby">
        <name type="near" plural="true">elevators</name>
        <link type="basic" dist="CLOSE" dir="S" area="providence_lobby_reception"/>
    </area>
    <area id="providence_lobby_showroom">
        <name type="in">showroom</name>
        <link type="basic" dist="CLOSE" dir="W" area="providence_lobby_reception"/>
    </area>
    <area id="providence_lobby_restroom">
        <name type="in">restroom</name>
        <object id="providence_lobby_restroom_door" template="door_basic">
            <localVar name="door_link_object">"providence_lobby_reception_restroom_door"</localVar>
            <localVar name="door_link_dir">"E"</localVar>
        </object>
    </area>
</data>

=== finley243/adventure-engine/src/gamefiles/data/world_city_test.xml
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/areas.xsd">
    <area id="street_corner_fifth_sinclair_1" room="street_corner_fifth_sinclair">
        <link type="basic" dist="CLOSE" dir="E" area="street_sinclair_fifth_sixth_1"/>
        <link type="basic" dist="CLOSE" dir="S" area="street_fifth_sinclair_archer_1"/>
    </area>
    <area id="street_corner_fifth_archer_1" room="street_corner_fifth_archer">
        <link type="basic" dist="CLOSE" dir="E" area="street_archer_fifth_sixth_1"/>
        <link type="basic" dist="CLOSE" dir="N" area="street_fifth_sinclair_archer_2"/>
        <object id="wilsons_corner_store_exterior_door" template="door_basic">
            <localVar name="door_link_object">"wilsons_corner_store_door_exit"</localVar>
            <localVar name="door_link_dir">"NE"</localVar>
        </object>
    </area>
    <area id="street_corner_sixth_sinclair_1" room="street_corner_sixth_sinclair">
        <link type="basic" dist="CLOSE" dir="W" area="street_sinclair_fifth_sixth_3"/>
        <link type="basic" dist="CLOSE" dir="S" area="street_sixth_sinclair_archer_1"/>
    </area>
    <area id="street_corner_sixth_archer_1" room="street_corner_sixth_archer">
        <link type="basic" dist="CLOSE" dir="W" area="street_archer_fifth_sixth_3"/>
        <link type="basic" dist="CLOSE" dir="N" area="street_sixth_sinclair_archer_2"/>
    </area>
    <area id="street_sinclair_fifth_sixth_1" room="street_sinclair_fifth_sixth">
        <link type="basic" dist="CLOSE" dir="W" area="street_corner_fifth_sinclair_1"/>
        <link type="basic" dist="CLOSE" dir="E" area="street_sinclair_fifth_sixth_2"/>
    </area>
    <area id="street_sinclair_fifth_sixth_2" room="street_sinclair_fifth_sixth">
        <link type="basic" dist="CLOSE" dir="W" area="street_sinclair_fifth_sixth_1"/>
        <link type="basic" dist="CLOSE" dir="E" area="street_sinclair_fifth_sixth_3"/>
        <link type="basic" dist="CLOSE" dir="S" area="alley_archer_fifth_sixth_1"/>
    </area>
    <area id="street_sinclair_fifth_sixth_3" room="street_sinclair_fifth_sixth">
        <link type="basic" dist="CLOSE" dir="W" area="street_sinclair_fifth_sixth_2"/>
        <link type="basic" dist="CLOSE" dir="E" area="street_corner_sixth_sinclair_1"/>
    </area>
    <area id="street_archer_fifth_sixth_1" room="street_archer_fifth_sixth">
        <link type="basic" dist="CLOSE" dir="W" area="street_corner_fifth_archer_1"/>
        <link type="basic" dist="CLOSE" dir="E" area="street_archer_fifth_sixth_2"/>
        <object id="wilsons_corner_store_exterior_vending_machine" template="vending_machine_nitron"/>
        <object id="archer_apartments_exterior_door" template="door_basic">
            <localVar name="door_link_object">"archer_apartments_entrance_door"</localVar>
            <localVar name="door_link_dir">"N"</localVar>
        </object>
    </area>
    <area id="street_archer_fifth_sixth_2" room="street_archer_fifth_sixth">
        <link type="basic" dist="CLOSE" dir="W" area="street_archer_fifth_sixth_1"/>
        <link type="basic" dist="CLOSE" dir="E" area="street_archer_fifth_sixth_3"/>
        <link type="basic" dist="CLOSE" dir="N" area="alley_archer_fifth_sixth_3"/>
    </area>
    <area id="street_archer_fifth_sixth_3" room="street_archer_fifth_sixth">
        <link type="basic" dist="CLOSE" dir="W" area="street_archer_fifth_sixth_2"/>
        <link type="basic" dist="CLOSE" dir="E" area="street_corner_sixth_archer_1"/>
    </area>
    <area id="street_fifth_sinclair_archer_1" room="street_fifth_sinclair_archer">
        <link type="basic" dist="CLOSE" dir="S" area="street_fifth_sinclair_archer_2"/>
        <link type="basic" dist="CLOSE" dir="N" area="street_corner_fifth_sinclair_1"/>
    </area>
    <area id="street_fifth_sinclair_archer_2" room="street_fifth_sinclair_archer">
        <link type="basic" dist="CLOSE" dir="N" area="street_fifth_sinclair_archer_1"/>
        <link type="basic" dist="CLOSE" dir="S" area="street_corner_fifth_archer_1"/>
        <object id="test_motorcycle" template="motorcycle"/>
    </area>
    <area id="street_sixth_sinclair_archer_1" room="street_sixth_sinclair_archer">
        <link type="basic" dist="CLOSE" dir="S" area="street_sixth_sinclair_archer_2"/>
        <link type="basic" dist="CLOSE" dir="N" area="street_corner_sixth_sinclair_1"/>
    </area>
    <area id="street_sixth_sinclair_archer_2" room="street_sixth_sinclair_archer">
        <link type="basic" dist="CLOSE" dir="N" area="street_sixth_sinclair_archer_1"/>
        <link type="basic" dist="CLOSE" dir="S" area="street_corner_sixth_archer_1"/>
    </area>
    <area id="alley_archer_fifth_sixth_1" room="alley_archer_fifth_sixth">
        <link type="basic" dist="CLOSE" dir="N" area="street_sinclair_fifth_sixth_2"/>
        <link type="basic" dist="CLOSE" dir="S" area="alley_archer_fifth_sixth_2"/>
    </area>
    <area id="alley_archer_fifth_sixth_2" room="alley_archer_fifth_sixth">
        <link type="basic" dist="CLOSE" dir="N" area="alley_archer_fifth_sixth_1"/>
        <link type="basic" dist="CLOSE" dir="S" area="alley_archer_fifth_sixth_3"/>
        <object id="wilsons_corner_store_exterior_backroom_door" template="door_basic">
            <localVar name="door_link_object">"wilsons_corner_store_backroom_exit"</localVar>
            <localVar name="door_link_dir">"W"</localVar>
        </object>
    </area>
    <area id="alley_archer_fifth_sixth_3" room="alley_archer_fifth_sixth">
        <link type="basic" dist="CLOSE" dir="N" area="alley_archer_fifth_sixth_2"/>
        <link type="basic" dist="CLOSE" dir="S" area="street_archer_fifth_sixth_2"/>
    </area>
</data>

=== finley243/adventure-engine/src/gamefiles/data/world_combat_test.xml
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/areas.xsd">
    <area id="warehouse_aisle_back">
        <name type="in">back aisle</name>
        <link type="basic" dist="CLOSE" dir="S" area="warehouse_aisle_front"/>
        <actor id="warehouse_enemy_1" template="enemy">
            <descriptor>greasy-haired</descriptor>
        </actor>
        <actor id="warehouse_enemy_2" template="enemy_melee">
            <descriptor>burly</descriptor>
        </actor>
    </area>
    <area id="warehouse_aisle_front">
        <name type="in">front aisle</name>
        <link type="basic" dist="CLOSE" dir="N" area="warehouse_aisle_back"/>
        <link type="basic" dist="CLOSE" dir="S" area="warehouse_bay_doors"/>
        <actor id="warehouse_enemy_3" template="enemy">
            <descriptor>tattooed</descriptor>
        </actor>
    </area>
    <area id="warehouse_bay_doors">
        <name type="near" plural="true">loading dock doors</name>
        <link type="basic" dist="CLOSE" dir="N" area="warehouse_aisle_front"/>
    </area>
</data>

=== finley243/adventure-engine/src/gamefiles/data/world_city_test_interiors.xml
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/areas.xsd">
    <area id="wilsons_corner_store_entrance" room="wilsons_corner_store">
        <name type="near">entrance</name>
        <link type="basic" dist="CLOSE" dir="N" area="wilsons_corner_store_shelves"/>
        <object id="wilsons_corner_store_door_exit" template="door_basic">
            <localVar name="door_link_object">"wilsons_corner_store_exterior_door"</localVar>
            <localVar name="door_link_dir">"SW"</localVar>
        </object>
        <object id="wilsons_corner_store_counter" template="counter"/>
        <actor id="frank_wilson" template="frank_wilson">
            <behaviors>
                <behavior type="procedure" isCycle="true">
                    <behavior type="move" area="wilsons_corner_store_entrance" duration="6">
                        <idle>
                            <phrase>$actor {yawn$s|stretch$es|tap$s $actor's fingers rhythmically on the counter|look$s across the store|check$s something under the counter, then straighten$s back up|glance$s out the window}.</phrase>
                        </idle>
                    </behavior>
                    <behavior type="move" area="wilsons_corner_store_backroom_area" duration="1"/>
                </behavior>
            </behaviors>
        </actor>
    </area>
    <area id="wilsons_corner_store_shelves" room="wilsons_corner_store">
        <name type="near" plural="true">shelves</name>
        <description>
            <line>The coolers cast a cool white glow across the linoleum floor. The air is colder here than at the front of the store, and a low hum echoes off the walls.</line>
        </description>
        <link type="basic" dist="CLOSE" dir="S" area="wilsons_corner_store_entrance"/>
        <object id="wilsons_corner_store_shelf" template="store_shelf_snacks"/>
        <object id="wilsons_corner_store_cooler" template="store_cooler_soft_drinks"/>
        <object id="wilsons_corner_store_network_port" template="network_port">
            <localVar name="networkID">"wilsons_corner_store"</localVar>
        </object>
        <object id="wilsons_corner_store_backroom_door" template="door_basic">
            <localVar name="door_link_object">"wilsons_corner_store_backroom_door_interior"</localVar>
            <localVar name="door_link_dir">"E"</localVar>
        </object>
    </area>
    <area id="wilsons_corner_store_backroom_area">
        <name type="in">backroom</name>
        <object id="wilsons_corner_store_backroom_door_interior" template="door_basic">
            <localVar name="door_link_object">"wilsons_corner_store_backroom_door"</localVar>
            <localVar name="door_link_dir">"W"</localVar>
        </object>
        <object id="wilsons_corner_store_backroom_exit" template="door_basic">
            <localVar name="door_link_object">"wilsons_corner_store_exterior_backroom_door"</localVar>
            <localVar name="door_link_dir">"E"</localVar>
        </object>
    </area>
    <area id="archer_apartments_entrance_front" room="archer_apartments_entrance">
        <name type="near">entrance</name>
        <link type="basic" dist="CLOSE" dir="N" area="archer_apartments_entrance_stairs"/>
        <object id="archer_apartments_entrance_door" template="door_basic">
            <localVar name="door_link_object">"archer_apartments_exterior_door"</localVar>
            <localVar name="door_link_dir">"S"</localVar>
        </object>
    </area>
    <area id="archer_apartments_entrance_stairs" room="archer_apartments_entrance">
        <name type="near">stairs</name>
        <link type="basic" dist="CLOSE" dir="S" area="archer_apartments_entrance_front"/>
    </area>
</data>
