=== finley243/adventure-engine/src/gamefiles/schemas/attack_types.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:include schemaLocation="common.xsd"/>

    <xs:element name="data">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="attackType" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="prompt" type="xs:string"/>
                            <xs:element name="attackPhrase" type="xs:string" minOccurs="0"/>
                            <xs:element name="attackOverallPhrase" type="xs:string" minOccurs="0"/>
                            <xs:element name="attackPhraseAudible" type="xs:string" minOccurs="0"/>
                            <xs:element name="attackOverallPhraseAudible" type="xs:string" minOccurs="0"/>
                            <xs:element name="damage" type="xs:string" minOccurs="0"/>
                            <xs:element name="hitChance" type="xs:string" minOccurs="0"/>
                            <xs:element name="hitChanceOverall" type="xs:string" minOccurs="0"/>
                            <xs:element name="range" type="DistanceCategory" minOccurs="0" maxOccurs="unbounded"/>
                            <xs:element name="targetEffect" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                        <xs:attribute name="category" type="AttackCategory" use="required"/>
                        <xs:attribute name="ammoConsumed" type="xs:integer"/>
                        <xs:attribute name="actionPoints" type="xs:integer"/>
                        <xs:attribute name="weaponConsumeType" type="WeaponConsumeType"/>
                        <xs:attribute name="nonIdealRange" type="xs:boolean"/>
                        <xs:attribute name="rate" type="xs:integer"/>
                        <xs:attribute name="damageMult" type="xs:decimal"/>
                        <xs:attribute name="damageType" type="xs:string"/>
                        <xs:attribute name="armorMult" type="xs:decimal"/>
                        <xs:attribute name="overrideEffects" type="xs:boolean"/>
                        <xs:attribute name="hitChanceMult" type="xs:decimal"/>
                        <xs:attribute name="isLoudOverride" type="xs:boolean"/>
                    </xs:complexType>
                    <xs:unique name="uniqueRange">
                        <xs:selector xpath="range"/>
                        <xs:field xpath="."/>
                    </xs:unique>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueID">
            <xs:selector xpath="attackType"/>
            <xs:field xpath="@id"/>
        </xs:unique>
    </xs:element>

    <xs:simpleType name="AttackCategory">
        <xs:restriction base="xs:string">
            <xs:enumeration value="single"/>
            <xs:enumeration value="targeted"/>
            <xs:enumeration value="spread"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="WeaponConsumeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="none"/>
            <xs:enumeration value="place"/>
            <xs:enumeration value="destroy"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== finley243/adventure-engine/src/gamefiles/data/attack_types.xml
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/attack_types.xsd">
    <attackType id="basic_ranged" category="single" ammoConsumed="1">
        <prompt>Attack</prompt>
        <attackPhrase>@rangedAttack</attackPhrase>
        <hitChance>hit_chance_skill(context.parentItem.skill, null)</hitChance>
    </attackType>
    <attackType id="basic_melee" category="single" ammoConsumed="1">
        <prompt>Attack</prompt>
        <attackPhrase>@meleeAttack</attackPhrase>
        <hitChance>hit_chance_skill(context.parentItem.skill, "dodge")</hitChance>
    </attackType>
    <attackType id="targeted_ranged" category="targeted" ammoConsumed="1">
        <prompt>Targeted Attack</prompt>
        <attackPhrase>@rangedAttackLimb</attackPhrase>
        <hitChance>hit_chance_skill(context.parentItem.skill, null)</hitChance>
    </attackType>
    <attackType id="targeted_melee" category="targeted" ammoConsumed="1">
        <prompt>Targeted Attack</prompt>
        <attackPhrase>@meleeAttackLimb</attackPhrase>
        <hitChance>hit_chance_skill(context.parentItem.skill, "dodge")</hitChance>
    </attackType>
    <attackType id="spread_ranged" category="spread" ammoConsumed="1">
        <prompt>Spread Attack</prompt>
        <attackPhrase>@rangedAttack</attackPhrase>
        <hitChance>hit_chance_skill(context.parentItem.skill, null)</hitChance>
    </attackType>
    <attackType id="spread_melee" category="spread" ammoConsumed="1">
        <prompt>Spread Attack</prompt>
        <attackPhrase>@meleeAttack</attackPhrase>
        <hitChance>hit_chance_skill(context.parentItem.skill, "dodge")</hitChance>
    </attackType>
    <attackType id="autofire" category="single" ammoConsumed="3" rate="1" damageMult="2.0" hitChanceMult="-0.4">
        <prompt>Autofire</prompt>
        <attackPhrase>@rangedAutoAttack</attackPhrase>
        <hitChance>hit_chance_skill(context.parentItem.skill, null)</hitChance>
    </attackType>
    <attackType id="grenade" category="spread" ammoConsumed="0" weaponConsumeType="destroy">
        <prompt>Throw</prompt>
        <attackPhrase>@grenadeAttack</attackPhrase>
        <hitChanceOverall>hit_chance_skill(context.parentItem.skill, null)</hitChanceOverall>
    </attackType>
    <attackType id="punch" category="single" ammoConsumed="0" rate="2" damageType="physical" armorMult="1.0" isLoudOverride="false">
        <prompt>Punch</prompt>
        <attackPhrase>@punchAttack</attackPhrase>
        <damage>5</damage>
        <hitChance>hit_chance_skill("melee", "dodge")</hitChance>
        <range>NEAR</range>
    </attackType>
</data>
