=== finley243/adventure-engine/src/gamefiles/schemas/factions.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:include schemaLocation="common.xsd"/>

    <xs:element name="data">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="faction" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="relation" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="faction" type="xs:string" use="required"/>
                                    <xs:attribute name="type" type="FactionRelation" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                        <xs:attribute name="default" type="FactionRelation"/>
                    </xs:complexType>
                    <xs:unique name="uniqueFactionId">
                        <xs:selector xpath="relation"/>
                        <xs:field xpath="@faction"/>
                    </xs:unique>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueId">
            <xs:selector xpath="faction"/>
            <xs:field xpath="@id"/>
        </xs:unique>
    </xs:element>

</xs:schema>

=== finley243/adventure-engine/src/gamefiles/data/factions.xml
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/factions.xsd">
    <faction id="default" default="NEUTRAL"/>
    <faction id="player" default="NEUTRAL"/>
    <faction id="stratis_hotel_staff" default="NEUTRAL">
        <relation faction="enemy" type="HOSTILE"/>
    </faction>
    <faction id="enemy" default="HOSTILE">
        <relation faction="stratis_hotel_staff" type="HOSTILE"/>
    </faction>
    <faction id="nexus_staff" default="NEUTRAL"/>
    <faction id="cornerstore_staff" default="NEUTRAL"/>
</data>
