=== finley243/adventure-engine/src/gamefiles/schemas/loot_tables.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:include schemaLocation="common.xsd"/>

    <xs:element name="data">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="lootTable" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:choice minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="item" type="LootEntry"/>
                            <xs:element name="table" type="LootEntry"/>
                        </xs:choice>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                        <xs:attribute name="useAll" type="xs:boolean"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueID">
            <xs:selector xpath="lootTable"/>
            <xs:field xpath="@id"/>
        </xs:unique>
    </xs:element>

</xs:schema>

=== finley243/adventure-engine/src/gamefiles/data/loot_tables.xml
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/loot_tables.xsd">
    <lootTable id="weapon_melee" useAll="false">
        <item>baseball_bat</item>
        <item>katana</item>
    </lootTable>
    <lootTable id="weapon_ranged" useAll="false">
        <item>pistol_light</item>
        <item>pistol_heavy</item>
        <item>rifle_auto</item>
    </lootTable>
    <lootTable id="ammo_random">
        <item countMin="5" countMax="20">ammo_pistol</item>
        <item countMin="5" countMax="20">ammo_rifle</item>
    </lootTable>
    <lootTable id="junk_random">
        <item>can_soda</item>
        <item>can_aluminum</item>
        <item>scrap_wires</item>
        <item>bag_plastic</item>
        <item>ecig_cartridge</item>
        <item>bottle_pill</item>
        <item>cup_paper</item>
        <item>can_spray_paint</item>
    </lootTable>
    <lootTable id="vendor_cornerstore">
        <table count="5">junk_random</table>
    </lootTable>
    <lootTable id="vendor_bigburger" useAll="true">
        <item countMin="20" countMax="40">burger</item>
        <item countMin="20" countMax="40">burger_cheese</item>
        <item countMin="20" countMax="40">burger_deluxe</item>
        <item countMin="20" countMax="40">french_fries</item>
        <item countMin="10" countMax="20">nitron_cola</item>
        <item countMin="10" countMax="20">nitron_diet</item>
    </lootTable>
    <lootTable id="store_snacks" useAll="true">
        <item countMin="2" countMax="10">nutri_chips_bacon</item>
        <item countMin="2" countMax="10">nutri_chips_wasabi</item>
    </lootTable>
    <lootTable id="store_soft_drinks" useAll="true">
        <item countMin="2" countMax="10">nitron_cola</item>
        <item countMin="2" countMax="10">nitron_diet</item>
    </lootTable>
</data>
