=== finley243/adventure-engine/src/gamefiles/schemas/networks.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:include schemaLocation="common.xsd"/>

    <xs:element name="data">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="node" type="NetworkNode" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueNodeID">
            <xs:selector xpath="node"/>
            <xs:field xpath="@id"/>
        </xs:unique>
    </xs:element>

    <xs:complexType name="NetworkNode">
        <xs:sequence>
            <xs:element name="name" type="xs:string" minOccurs="0"/>
            <xs:element name="node" type="NetworkNode" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string"/>
        <xs:attribute name="type" type="NodeType"/>
        <xs:attribute name="scene" type="xs:string"/>
        <xs:attribute name="object" type="xs:string"/>
    </xs:complexType>

    <xs:simpleType name="NodeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="data"/>
            <xs:enumeration value="control"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== finley243/adventure-engine/src/gamefiles/data/networks.xml
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/networks.xsd">
    <node id="wilsons_corner_store_main">
        <name>node_main</name>
        <node id="wilsons_corner_store_devices">
            <name>device_system</name>
            <node id="wilsons_corner_store_purchase_logs" type="data" scene="wilsons_corner_store_purchase_logs">
                <name>purchase_logs</name>
            </node>
            <node id="wilsons_corner_store_gumball_machine" type="control" object="wilsons_corner_store_gumball_machine">
                <name>gumball_machine_01</name>
            </node>
        </node>
    </node>
    <scene id="wilsons_corner_store_purchase_logs">
        <line>Purchase history corrupted.</line>
        <line>Please load backup file to continue.</line>
    </scene>
</data>
