=== finley243/adventure-engine/src/gamefiles/schemas/objects.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:include schemaLocation="common.xsd"/>

    <xs:element name="data">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="object" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="proper" type="xs:boolean"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="description" type="SceneLine" minOccurs="0"/>
                            <xs:element name="damage" type="DamageResistance" minOccurs="0" maxOccurs="unbounded"/>
                            <xs:element name="script" type="ScriptWithTrigger" minOccurs="0" maxOccurs="unbounded"/>
                            <xs:element name="action" type="CustomAction" minOccurs="0" maxOccurs="unbounded"/>
                            <xs:element name="networkAction" type="CustomAction" minOccurs="0" maxOccurs="unbounded"/>
                            <xs:element name="component" type="ObjectComponent" minOccurs="0" maxOccurs="unbounded"/>
                            <xs:element name="localVar" type="LocalVar" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                        <xs:attribute name="maxHP" type="xs:integer"/>
                    </xs:complexType>
                    <xs:unique name="uniqueDamageType">
                        <xs:selector xpath="damage"/>
                        <xs:field xpath="@type"/>
                    </xs:unique>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueID">
            <xs:selector xpath="object"/>
            <xs:field xpath="@id"/>
        </xs:unique>
    </xs:element>

    <xs:complexType name="ObjectComponent">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <!-- inventory -->
            <xs:element name="takePrompt" type="xs:string"/>
            <xs:element name="takePhrase" type="xs:string"/>
            <xs:element name="storePrompt" type="xs:string"/>
            <xs:element name="storePhrase" type="xs:string"/>
            <xs:element name="inventory" type="InlineLootTable"/>
            <xs:element name="itemAction" type="CustomAction"/>
            <!-- link -->
            <xs:element name="link" type="LinkEntry"/>
            <!-- usable -->
            <xs:element name="slot" type="UsableSlot"/>
        </xs:choice>
        <xs:attribute name="type" type="ComponentType" use="required"/>
        <xs:attribute name="startEnabled" type="xs:boolean"/>
        <xs:attribute name="restricted" type="xs:boolean"/>
        <!-- inventory -->
        <xs:attribute name="enableTake" type="xs:boolean"/>
        <xs:attribute name="enableStore" type="xs:boolean"/>
        <!-- vehicle -->
        <xs:attribute name="vehicleType" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="LinkEntry">
        <xs:sequence>
            <xs:element name="conditionMovable" type="xs:string" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string"/>
        <xs:attribute name="moveAction" type="xs:string"/>
        <xs:attribute name="visible" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="UsableSlot">
        <xs:sequence>
            <xs:element name="startPhrase" type="xs:string"/>
            <xs:element name="endPhrase" type="xs:string"/>
            <xs:element name="startPrompt" type="xs:string"/>
            <xs:element name="endPrompt" type="xs:string"/>
            <xs:element name="exposedComponent" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="usingAction" type="CustomAction" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
        <xs:attribute name="cover" type="xs:boolean"/>
        <xs:attribute name="hidden" type="xs:boolean"/>
        <xs:attribute name="seeOtherAreas" type="xs:boolean"/>
        <xs:attribute name="localActions" type="xs:boolean"/>
        <xs:attribute name="parentActions" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="DamageResistance">
        <xs:attribute name="type" type="xs:string" use="required"/>
        <xs:attribute name="resistance" type="xs:integer"/>
        <xs:attribute name="mult" type="xs:decimal"/>
    </xs:complexType>

    <xs:complexType name="LocalVar">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="ComponentType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="inventory"/>
            <xs:enumeration value="link"/>
            <xs:enumeration value="network"/>
            <xs:enumeration value="usable"/>
            <xs:enumeration value="vehicle"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== finley243/adventure-engine/src/gamefiles/data/objects.xml
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/objects.xsd">
    <object id="door_basic">
        <name>door</name>
        <component type="link">
            <link id="door_link" moveAction="move_door" visible="false"/>
        </component>
    </object>
    <object id="door_fake">
        <name>door</name>
    </object>
    <object id="door_locked">
        <name>door</name>
        <action template="lock_key"/>
        <action template="lock_pick"/>
        <component type="link">
            <link id="door_link" moveAction="move_door" visible="false">
                <conditionMovable>!stat.parentObject.locked</conditionMovable>
            </link>
        </component>
        <localVar name="locked">true</localVar>
        <localVar name="lock_keys">null</localVar>
        <localVar name="lock_pick_difficulty">1</localVar>
    </object>
    <object id="chair_plastic">
        <name>plastic chair</name>
        <component type="usable">
            <slot id="seat">
                <startPhrase>@sit</startPhrase>
                <endPhrase>@getUp</endPhrase>
                <startPrompt>Sit</startPrompt>
                <endPrompt>Stand</endPrompt>
            </slot>
        </component>
    </object>
    <object id="counter">
        <name>counter</name>
    </object>
    <object id="gumball_machine">
        <name>gumball machine</name>
        <action template="vending_machine">
            <parameter name="itemID">"gumball"</parameter>
        </action>
        <networkAction template="vending_machine_hack_price"/>
        <localVar name="price_hacked">false</localVar>
    </object>
    <object id="garbage_bin">
        <name>garbage bin</name>
        <component type="inventory">
            <takePrompt>Take</takePrompt>
            <takePhrase>@takeFrom</takePhrase>
            <storePrompt>Store</storePrompt>
            <storePhrase>@storeIn</storePhrase>
            <inventory>
                <table countMin="0" countMax="3">junk_random</table>
            </inventory>
        </component>
    </object>
    <object id="store_shelf_snacks">
        <name>snacks shelf</name>
        <component type="inventory">
            <takePrompt>Take</takePrompt>
            <takePhrase>@takeFrom</takePhrase>
            <storePrompt>Place</storePrompt>
            <storePhrase>@placeOn</storePhrase>
            <inventory>
                <table>store_snacks</table>
            </inventory>
        </component>
    </object>
    <object id="store_shelf_meals">
        <name>meal shelf</name>
        <component type="inventory">
            <takePrompt>Take</takePrompt>
            <takePhrase>@takeFrom</takePhrase>
            <storePrompt>Place</storePrompt>
            <storePhrase>@placeOn</storePhrase>
            <inventory>
                <table>store_snacks</table>
            </inventory>
        </component>
    </object>
    <object id="store_shelf_alcohol">
        <name>alcohol shelf</name>
        <component type="inventory">
            <takePrompt>Take</takePrompt>
            <takePhrase>@takeFrom</takePhrase>
            <storePrompt>Place</storePrompt>
            <storePhrase>@placeOn</storePhrase>
            <inventory>
                <table>store_snacks</table>
            </inventory>
        </component>
    </object>
    <object id="store_shelf_medicine">
        <name>medicine shelf</name>
        <component type="inventory">
            <takePrompt>Take</takePrompt>
            <takePhrase>@takeFrom</takePhrase>
            <storePrompt>Place</storePrompt>
            <storePhrase>@placeOn</storePhrase>
            <inventory>
                <table>store_snacks</table>
            </inventory>
        </component>
    </object>
    <object id="store_cooler_soft_drinks">
        <name>soft drinks cooler</name>
        <component type="inventory">
            <takePrompt>Take</takePrompt>
            <takePhrase>@takeFrom</takePhrase>
            <storePrompt>Store</storePrompt>
            <storePhrase>@storeIn</storePhrase>
            <inventory>
                <table>store_soft_drinks</table>
            </inventory>
        </component>
    </object>
    <object id="store_cooler_alcohol">
        <name>alcohol cooler</name>
        <component type="inventory">
            <takePrompt>Take</takePrompt>
            <takePhrase>@takeFrom</takePhrase>
            <storePrompt>Store</storePrompt>
            <storePhrase>@storeIn</storePhrase>
            <inventory>
                <table>store_soft_drinks</table>
            </inventory>
        </component>
    </object>
    <object id="vending_machine_nitron">
        <name>Nitron Cola vending machine</name>
        <action template="vending_machine">
            <parameter name="itemID">"nitron_cola"</parameter>
        </action>
        <action template="vending_machine">
            <parameter name="itemID">"nitron_diet"</parameter>
        </action>
        <networkAction template="vending_machine_hack_price"/>
        <localVar name="price_hacked">false</localVar>
    </object>
    <object id="motorcycle">
        <name>motorcycle</name>
        <component type="vehicle" restricted="true" vehicleType="motorcycle"/>
        <component type="usable">
            <slot id="seat">
                <startPhrase>@sit</startPhrase>
                <endPhrase>@getUp</endPhrase>
                <startPrompt>Sit</startPrompt>
                <endPrompt>Stand</endPrompt>
                <exposedComponent>vehicle</exposedComponent>
            </slot>
        </component>
    </object>
    <object id="network_port">
        <name>network port</name>
        <component type="usable">
            <slot id="port">
                <startPhrase>@jackIn</startPhrase>
                <endPhrase>@jackOut</endPhrase>
                <startPrompt>Jack In</startPrompt>
                <endPrompt>Jack Out</endPrompt>
                <exposedComponent>network</exposedComponent>
            </slot>
        </component>
        <component type="network" restricted="true"/>
    </object>
</data>
