=== finley243/adventure-engine/src/gamefiles/schemas/rooms.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:include schemaLocation="common.xsd"/>

    <xs:element name="data">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="room" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="proper" type="xs:boolean"/>
                                            <xs:attribute name="type" type="AreaNameType"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="description" type="SceneLine" minOccurs="0"/>
                            <xs:element name="script" type="ScriptWithTrigger" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                        <xs:attribute name="faction" type="xs:string"/>
                        <xs:attribute name="restriction" type="RestrictionType"/>
                        <xs:attribute name="allowAllies" type="xs:boolean"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueId">
            <xs:selector xpath="room"/>
            <xs:field xpath="@id"/>
        </xs:unique>
    </xs:element>

</xs:schema>

=== finley243/adventure-engine/src/gamefiles/data/rooms.xml
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/rooms.xsd">
    <room id="street_corner_fifth_sinclair">
        <name proper="false" type="in">intersection</name>
    </room>
    <room id="street_corner_fifth_archer">
        <name proper="false" type="in">intersection</name>
    </room>
    <room id="street_corner_sixth_sinclair">
        <name proper="false" type="in">intersection</name>
    </room>
    <room id="street_corner_sixth_archer">
        <name proper="false" type="in">intersection</name>
    </room>
    <room id="street_sinclair_fifth_sixth">
        <name proper="true" type="on">Sinclair Street</name>
    </room>
    <room id="street_archer_fifth_sixth">
        <name proper="true" type="on">Archer Street</name>
    </room>
    <room id="street_fifth_sinclair_archer">
        <name proper="true" type="on">5th Avenue</name>
    </room>
    <room id="street_sixth_sinclair_archer">
        <name proper="true" type="on">6th Avenue</name>
    </room>
    <room id="alley_archer_fifth_sixth">
        <name proper="false" type="in">alley</name>
    </room>
    <room id="sinclair_tech_store">
        <name proper="true">Argon Electronics</name>
    </room>
    <room id="wilsons_corner_store">
        <name proper="true">Wilson's corner store</name>
        <description>
            <line>The store is small, with no wasted space. Near the entrance is the checkout counter. To the north are shelves stocked with various goods, with a row of coolers behind them.</line>
        </description>
    </room>
    <room id="archer_burger_restaurant">
        <name>BigBurger</name>
    </room>
    <room id="archer_apartments_entrance">
        <name>apartments</name>
    </room>
    <room id="archer_apartments_23">
        <name proper="true">apartment 23</name>
    </room>
    <room id="warehouse">
        <name>warehouse</name>
    </room>
    <room id="providence_lobby">
        <name>lobby</name>
    </room>
</data>
