=== finley243/adventure-engine/src/gamefiles/schemas/skills.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="data">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="skill" type="NamedEntry" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueSkillId">
            <xs:selector xpath="skill"/>
            <xs:field xpath="@id"/>
        </xs:unique>
    </xs:element>

    <xs:complexType name="NamedEntry">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="id" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

</xs:schema>

=== finley243/adventure-engine/src/gamefiles/data/skills.xml
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/skills.xsd">
    <skill id="melee">melee</skill>
    <skill id="throwing">throwing</skill>
    <skill id="intimidation">intimidation</skill>
    <skill id="software">software</skill>
    <skill id="hardware">hardware</skill>
    <skill id="medicine">medicine</skill>
    <skill id="barter">barter</skill>
    <skill id="persuasion">persuasion</skill>
    <skill id="deception">deception</skill>
    <skill id="handguns">handguns</skill>
    <skill id="long_arms">long arms</skill>
    <skill id="lockpick">lockpick</skill>
    <skill id="stealth">stealth</skill>
    <skill id="dodge">dodge</skill>
</data>
