=== finley243/adventure-engine/src/gamefiles/schemas/weapon_classes.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:include schemaLocation="common.xsd"/>

    <xs:element name="data">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="weaponClass" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="range" type="DistanceCategory" maxOccurs="unbounded"/>
                            <xs:element name="attackType" type="xs:string" maxOccurs="unbounded"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                        <xs:attribute name="isRanged" type="xs:boolean" use="required"/>
                        <xs:attribute name="isLoud" type="xs:boolean" use="required"/>
                        <xs:attribute name="skill" type="xs:string" use="required"/>
                    </xs:complexType>
                    <xs:unique name="uniqueRanges">
                        <xs:selector xpath="range"/>
                        <xs:field xpath="."/>
                    </xs:unique>
                    <xs:unique name="uniqueAttackTypes">
                        <xs:selector xpath="attackType"/>
                        <xs:field xpath="."/>
                    </xs:unique>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueID">
            <xs:selector xpath="weaponClass"/>
            <xs:field xpath="@id"/>
        </xs:unique>
    </xs:element>

</xs:schema>

=== finley243/adventure-engine/src/gamefiles/data/weapon_classes.xml
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/weapon_classes.xsd">
    <weaponClass id="pistol" isRanged="true" isLoud="true" skill="handguns">
        <name>pistol</name>
        <range>CLOSE</range>
        <attackType>basic_ranged</attackType>
        <attackType>targeted_ranged</attackType>
    </weaponClass>
    <weaponClass id="smg" isRanged="true" isLoud="true" skill="handguns">
        <name>SMG</name>
        <range>CLOSE</range>
        <attackType>basic_ranged</attackType>
        <attackType>targeted_ranged</attackType>
        <attackType>autofire</attackType>
    </weaponClass>
    <weaponClass id="shotgun" isRanged="true" isLoud="true" skill="long_arms">
        <name>shotgun</name>
        <range>FAR</range>
        <attackType>basic_ranged</attackType>
        <attackType>targeted_ranged</attackType>
    </weaponClass>
    <weaponClass id="assault_rifle" isRanged="true" isLoud="true" skill="long_arms">
        <name>assault rifle</name>
        <range>FAR</range>
        <attackType>basic_ranged</attackType>
        <attackType>targeted_ranged</attackType>
        <attackType>autofire</attackType>
    </weaponClass>
    <weaponClass id="sniper_rifle" isRanged="true" isLoud="true" skill="long_arms">
        <name>sniper rifle</name>
        <range>DISTANT</range>
        <attackType>basic_ranged</attackType>
        <attackType>targeted_ranged</attackType>
    </weaponClass>
    <weaponClass id="knife" isRanged="false" isLoud="false" skill="melee">
        <name>knife</name>
        <range>NEAR</range>
        <attackType>basic_melee</attackType>
        <attackType>targeted_melee</attackType>
    </weaponClass>
    <weaponClass id="sword" isRanged="false" isLoud="false" skill="melee">
        <name>sword</name>
        <range>NEAR</range>
        <attackType>basic_melee</attackType>
        <attackType>targeted_melee</attackType>
    </weaponClass>
    <weaponClass id="club" isRanged="false" isLoud="false" skill="melee">
        <name>club</name>
        <range>NEAR</range>
        <attackType>basic_melee</attackType>
        <attackType>targeted_melee</attackType>
    </weaponClass>
    <weaponClass id="axe" isRanged="false" isLoud="false" skill="melee">
        <name>axe</name>
        <range>NEAR</range>
        <attackType>basic_melee</attackType>
        <attackType>targeted_melee</attackType>
    </weaponClass>
    <weaponClass id="grenade" isRanged="true" isLoud="true" skill="throwing">
        <name>grenade</name>
        <range>CLOSE</range>
        <attackType>grenade</attackType>
    </weaponClass>
</data>
